### ISSUE TITLE
Markbot slowed down

### ISSUE THREAD

**Issue by verajpatel** [verajpatel/frozen-not-in-time#1]
Markbot is slowed down due to my animations. @charlie-quinn

**Comment by charlie-quinn** [comment]
Here's a snippet of code that I used to help another student. Feel free to replace the classes used in this example with your own classes.

- [ ] add a `<div>` around everything inside of `<body>` and add a class (ex: outer-banner, background, etc.)
- [ ] target this new `<div>` and add the `background-image: repeating-linear-gradient...` to it
  - this will prevent the background-image from spilling out of its container
  - [ ] also add your top/bottom borders here
- [ ] remove all spacing properties from `.html` in your main.css file (these are unnecessary since we'll be targeting everything individually)
- [ ] position your entire ice-cream cone:
  - [ ] add the `.ice-cream` to the `<div>` wrapping all of your ice-cream ingredients
  - [ ] target this `<div>` in your main.css file and add a `min-height: 480px;` to it (this will help determine most of the height that we want to use)
  - [ ] add classes `wrapper` and `grid-middle` to the `<div class="grid>` around both your text and cone (this will add a max-width, forcing everything to sit a bit closet on our screen)
  - [ ] add the class `.ingredient` to all your `<img>` tags inside of your index.html file (this will allow us to target all of these objects at the same time and apply their common positioning/sizing properties)
    - [ ] remove all positioning properties from `.cherry, .vanilla-fudge, .chocolate-chip, .mint-chip, .cone` (because we will first target them all together using `ingredient`, then finesse their individual positioning if needed)
    - _I'll give you the animation properties here since many people had a hard time getting Markbot 🤖to approve:_
    - [ ] target `.cone` and apply `animation: cone-drop-in .3s ease-in forwards;`
    - [ ] target `.mint-chip` and apply `animation: mint-drop-in .3s .3s ease-in forwards;`
    - [ ] target `.chocolate-chip` and apply `animation: choc-drop-in .3s .6s ease-in forwards;`
    - [ ] target `.vanilla-fudge` and apply `animation: vanilla-drop-in .2s .9s ease-in forwards;`
    - [ ] target `.cherry` and apply `animation: cherry-drop-in .15s 1.5s ease-in forwards;`
- [ ] setup your `@keyframes` starting with the `.cone` and following the order outlined above ☝️ 
  - [ ] .cone { 
0% {
bottom: 100%;
}
100% {
    bottom: 0;
  }
  - [ ] .mint-chip {
  0% {
    bottom: 100%;
  }
  100% {
    bottom: 104px;
  }
}
  - [ ] adjust the  100% { bottom: `??px`;} until each ingredient falls into place

- [ ] ⚠️ if your ingredients seem too large, re-download the original `.ai` file and export each `.svg` without resizing anything

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
